// User and Settings Types
export type EducationLevel = 'middle-school' | 'high-school' | 'university';
export type AIMode = 'guided' | 'balanced' | 'direct';
export type Theme = 'light' | 'dark' | 'dim';
export type FontSize = 'sm' | 'base' | 'lg' | 'xl';
export type Priority = 'low' | 'medium' | 'high';

export interface UserSettings {
  userId: string;
  educationLevel: EducationLevel;
  subjects: string[];
  defaultAIMode: AIMode;
  theme: Theme;
  fontSize: FontSize;
  reducedMotion: boolean;
  dyslexicFont: boolean;
  confettiEnabled: boolean;
  voiceAutoPlay: boolean;
  voiceSpeed: number; // 0.5 to 2.0
  dueDateOffset: number; // days before due date to show warning
  dashboardLayout: string[]; // widget IDs in order
  dashboardWidgets: Record<string, boolean>; // widget visibility
  studyReminders: boolean;
  onboardingCompleted: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface User {
  id: string;
  email: string;
  displayName?: string;
  settings: UserSettings;
}

// Study and Progress Types
export interface Subject {
  id: string;
  userId: string;
  name: string;
  color?: string;
  icon?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Topic {
  id: string;
  userId: string;
  subjectId: string;
  name: string;
  description?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface StudyHub {
  id: string;
  userId: string;
  topicId: string;
  notes?: string;
  linkedMaterialIds: string[];
  createdAt: Date;
  updatedAt: Date;
}

// Assignment Types
export interface Assignment {
  id: string;
  userId: string;
  title: string;
  subjectId: string;
  dueDate: Date;
  priority: Priority;
  completed: boolean;
  questions?: Question[];
  createdAt: Date;
  updatedAt: Date;
}

export interface Question {
  id: string;
  assignmentId: string;
  content: string;
  imageUrl?: string;
  audioUrl?: string;
  extractedText?: string;
  steps?: SolutionStep[];
  completed: boolean;
  createdAt: Date;
}

export interface SolutionStep {
  id: string;
  questionId: string;
  stepNumber: number;
  explanation: string;
  equation?: string;
  confirmed: boolean;
  aiMode: AIMode;
  createdAt: Date;
}

// Flashcard Types
export interface Flashcard {
  id: string;
  userId: string;
  topicId: string;
  front: string;
  back: string;
  confidence: 1 | 2 | 3 | 4 | 5;
  nextReviewDate: Date;
  reviewCount: number;
  isAutoGenerated: boolean;
  createdAt: Date;
  updatedAt: Date;
}

// Test Types
export interface Test {
  id: string;
  userId: string;
  topicId: string;
  name: string;
  timeLimit?: number; // in minutes
  difficulty: 'easy' | 'medium' | 'hard';
  questionCount: number;
  examPressureMode: boolean;
  questions: TestQuestion[];
  completed: boolean;
  startedAt?: Date;
  completedAt?: Date;
  score?: number;
  analytics?: TestAnalytics;
  createdAt: Date;
}

export interface TestQuestion {
  id: string;
  testId: string;
  question: string;
  options?: string[];
  correctAnswer: string;
  userAnswer?: string;
  isCorrect?: boolean;
  timeSpent?: number; // in seconds
}

export interface TestAnalytics {
  testId: string;
  accuracyByTopic: Record<string, number>;
  averageSpeed: number;
  weakAreas: string[];
  recommendedNextSteps: string[];
}

// Material Types
export interface Material {
  id: string;
  userId: string;
  name: string;
  type: 'pdf' | 'image' | 'audio' | 'notes';
  url?: string;
  content?: string; // for text notes
  fileSize?: number;
  duration?: number; // for audio
  thumbnailUrl?: string;
  uploadedAt: Date;
  createdAt: Date;
}

// Lecture Types
export interface Lecture {
  id: string;
  userId: string;
  title: string;
  subjectId?: string;
  audioUrl: string;
  duration: number;
  summary?: string;
  keyPoints?: string[];
  generatedQuestions?: string[];
  notes?: string;
  linkedToHubIds: string[];
  recordedAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

// Streak and Milestone Types
export interface Streak {
  userId: string;
  currentStreak: number;
  longestStreak: number;
  lastStudyDate: Date;
  multiplier: number;
  updatedAt: Date;
}

export interface Milestone {
  id: string;
  userId: string;
  type: 'streak' | 'mastery' | 'assignment' | 'test';
  title: string;
  description: string;
  achievedAt: Date;
  value: number; // e.g., 7 for 7-day streak
}

// Weak Skill Tracking
export interface WeakSkill {
  id: string;
  userId: string;
  topicId: string;
  skill: string;
  detectedAt: Date;
  improvementScore: number; // 0-100
  lastPracticedAt?: Date;
}

// AI Response Types
export interface AIResponse {
  content: string;
  mode: AIMode;
  timestamp: Date;
  tokens?: number;
}

export interface AIConversation {
  id: string;
  userId: string;
  messages: AIMessage[];
  context: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface AIMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  imageUrl?: string;
  audioUrl?: string;
  timestamp: Date;
}
